### ISSUE TITLE
SMLM format tiling multiple fields of view

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/smlm-file-format#2]
Hi, 
I would like to know if it is possible to tile multiple fields of view, I saw you used deep zoom for this figure
![Capture du 2021-07-15 14-50-51](https://user-images.githubusercontent.com/56833522/125791001-544c38d7-e224-42bf-a53d-88c83ae7bb20.png)
How would this feature interact with smlm fomat ?
@oeway

**Comment by oeway** [comment]
To store these, it's rather straightforward, you just store all the tables in one file, then in the manifest, you can set the ` "offset": {'x':14, 'y':12 }` for each file. See the [smlm file specification](https://github.com/imodpasteur/smlm-file-format/blob/master/specification.md).

The part which is not implemented is how to display them.

**Comment by baiddd** [comment]
Thanks
